## REFRENSI: https://trackingapps.org/
## cloudimage.io from ade.anatasia@gmail.com

baseurl = "https://happy-island-06a857210.4.azurestaticapps.net/"
title = "Penyadap.web.id"
description = "Aplikasi Penyadap HP iPhone, Android, Blackberry untuk pasangan selingkuh."
copyright = "PENYADAP.WEB.ID. All rights reserved."

enableRobotsTXT = true

debug = 10000

### SETUP
languageCode = "id"
theme = "hugo_framework"
enableEmoji = true
disableHugoGeneratorInject= true
canonifyurls = true
[pagination]
  pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = false

[minify]
    [minify.tdewolff.html]
      keepQuotes = true
      keepWhitespace = true

[blackfriday]
  smartypants = false


[related]
  includeNewer = true
  threshold = 100
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100

[outputs]
home = ["HTML", "AMP",  "RSS"]
page = ["HTML", "AMP", "RSS"]


[mediaTypes]
[mediaTypes."application/rss"]
isPlainText = true
suffixes = ["xml"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "index"


## VENDOR


## TAXTONAMIES

[taxonomies]
  tag = "tags"
  category = "categories"
  label = "label"
  author = "authors"

## PERMALINK


## MENU
[[menu.home]]
    name = "Calls"
    pre = "fa fa-phone"
    weight = 1
    url = "/calls/"
    
[[menu.home]]
    name = "Location"
    pre = "icon-map"
    weight = 2
    url = "/locations/"
    
[[menu.home]]
    name = "Site Web"
    pre = "fa fa-chrome"
    weight = 3
    url = "/sites/"
    
[[menu.home]]
    name = "Instan Messaging (ROOT)"
    pre = "icon-eye"
    weight = 4
    url = "/instan-messaging-root/"
    
[[menu.home]]
    name = "Instan Messaging"
    pre = "icon-eye"
    weight = 5
    url = "/instan-messaging/"

[[menu.main]]
    name = "Disclaimer"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "disclaimer"
    url = "/disclaimer/"
    
[[menu.main]]
    name = "Support"
    pre = "<i class='fa fa-road'></i>"
    weight = -120
    identifier= "hubungi-kami"
    url = "/hubungi-kami/"

[[menu.main]]
    name = "Pemesanan"
    pre = "<i class='fa fa-road'></i>"
    weight = -130
    identifier= "Download"
    url = "/download/"

    
[[menu.footer]]
    name = "Demo Aplikasi"
    pre = " |"
    weight = -201
    url = "/"
[[menu.footer]]
    name = "Jasa Hack"
    pre = " |"
    weight = -200
    url = "/download/"
[[menu.footer]]
    name = "Blog"
    pre = " |"
    weight = -199
    url = "/konten/"
[[menu.footer]]
    name = "Ketentuan"
    pre = " |"
    weight = -198
    url = "/disclaimer/"
[[menu.footer]]
    name = "Privacy Police"
    pre = ""
    weight = -197
    url = "/privacy-police/"
[[menu.footer]]
    name = "Contact"
    pre = ""
    weight = -196
    url = "/hubungi-kami/"


[[menu.home]]
  identifier = "dashboard"
  name = "Dashboard"
  url = "/"
  weight = 1
  pre = "icon-home"
[[menu.home]]
  identifier = "sms"
  name = "SMS"
  url = "/sms/"
  weight = 2
  pre = "icon-envelope"
[[menu.home]]
  identifier = "mms"
  name = "MMS"
  url = "/mms/"
  weight = 3
  pre = "fa fa-file-image-o"
[[menu.home]]
  identifier = "calls"
  name = "Calls"
  url = "/#sasdasd"
  weight = 4
  pre = "fa fa-phone"
[[menu.home]]
  identifier = "location"
  name = "Location"
  url = "#"
  weight = 5
  pre = "icon-map"
[[menu.home]]
  identifier = "pictures"
  name = "Pictures"
  url = "/pictures/"
  weight = 6
  pre = "icon-picture"
[[menu.home]]
  identifier = "apps"
  name = "Applications"
  url = "/applications/"
  weight = 7
  pre = "icon-game-controller"
[[menu.home]]
  identifier = "calendar"
  name = "Calendar"
  url = "/calendar/"
  weight = 8
  pre = "fa fa-calendar"
[[menu.home]]
  identifier = "contacts"
  name = "Contacts"
  url = "/contact/"
  weight = 9
  pre = "icon-notebook"
[[menu.home]]
  identifier = "sites"
  name = "Site Web"
  url = "/#"
  weight = 10
  pre = "i fa fa-chrome"
[[menu.home]]
  identifier = "screenshot"
  name = "Screenshot"
  url = "/screenshot/"
  weight = 11
  pre = "fa fa-binoculars"
[[menu.home]]
  identifier = "chatroot"
  name = "Instan Messaging (ROOT)"
  url = "#"
  weight = 12
  pre = "fi icon-eye"
[[menu.home]]
  identifier = "chat"
  name = "Instan Messaging"
  url = "#"
  weight = 13
  pre = "i icon-eye"
[[menu.home]]
  identifier = "remote"
  name = "Remote Control"
  url = "/remote/"
  weight = 14
  pre = "fa fa-cloud"
[[menu.home]]
  identifier = "live"
  name = "Live Viewing"
  url = "/live/"
  weight = 15
  pre = "fa fa-video-camera"
[[menu.home]]
  identifier = "fileexplorer"
  name = "File Explorer"
  url = "/file-explorer/"
  weight = 16
  pre = "icon-folder-alt"
[[menu.home]]
  identifier = "restriction"
  name = "Schedule restriction"
  url = "/schedule-restriction/"
  weight = 17
  pre = "fa fa-lock"
[[menu.home]]
  identifier = "smscmd"
  name = "SMS Commands"
  url = "/sms-command/"
  weight = 18
  pre = "fa fa-send"
[[menu.home]]
  identifier = "stats"
  name = "Statistics"
  url = "/stats/"
  weight = 19
  pre = "fa fa-pie-chart"
[[menu.home]]
  identifier = "account"
  name = "My Account"
  url = "/account/"
  weight = 20
  pre = "i icon-user"


[params.features]
    enable = true
	
	
[params]
  ## SITE SETTING
  #
  siteLogo = "/logo.png"
  author = "Karnelius Jonny"
  nomer = "085645161031"
  nomer_url = "6287774686029"
  
  
  disqus = "pephone"
  twitter = "@penyadap_id"
    
  googleAnalytics = "UA-103506959-1"
  
  ## ADSENSE
  
  adsensePublisher = "ca-pub-8751263644994394"
  

  dateformat = "Jan 2, 2006" #Optional
  googlefonts = "https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" # Optional, Include google fonts.
  fontfamily = "'Roboto Slab', serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.
  
  
